version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  test_develop:
    jobs:
      - filters:
        branches:
          only:
            - Microtask1
      - cypress/install
      - cypress/run:
          name: firefox
          requires:
            - cypress/install 
          executor: cypress/browsers-chrome73-ff68
          browser: firefox
          start: npm run dev
          wait-on: http://0.0.0.0:8080
          command: npm run cypress:all
          group: firefox

      - cypress/run:
          name: chrome
          requires:
            - cypress/install
          executor: cypress/browsers-chrome73-ff68
          browser: chrome
          start: npm run dev
          wait-on: http://0.0.0.0:8080
          command: npm run cypress:all
          group: chrome